name: Trigger auto deployment for container-app-qrbpywgqcr3la

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-qrbpywgqcr3la-AutoDeployTrigger-a5934388-160f-48b7-897d-2e414e283bcf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQRBPYWGQCR3LA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQRBPYWGQCR3LA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQRBPYWGQCR3LA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPQRBPYWGQCR3LA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQRBPYWGQCR3LA_REGISTRY_PASSWORD }}
          containerAppName: container-app-qrbpywgqcr3la
          resourceGroup: appspacesragapp9506a388
          imageToBuild: default/container-app-qrbpywgqcr3la:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


